### PR TITLE
Improved index.html

### PR DESCRIPTION
**Pull request by FTS18**

### CODE REVIEW

**Review by lahiruroot — APPROVED** [review]

**Comment by FTS18** [comment]
**Improved** the code and **added** some more **tags** and **styling** in the last commit
[Subscribe to my youtube channel](https://youtube.com/c/spacify18)

**Review by lahiruroot — APPROVED** [review]
Confirmed

**Review by lahiruroot — APPROVED** [review]

**Comment by FTS18** [comment]
Please merge the pull request if u found it useful

**Comment by FTS18** [comment]
When are you merging the approved PR's?

**Pull request closed without merging**
